### ISSUE TITLE
Caddy not restarting after reboot on Debian 10

### ISSUE THREAD

**Issue by udf2457** [caddyserver/dist#63] opened 2021-05-29 11:35 UTC
Using Caddy from sourcesmith (deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main) on Debian 10.9, I am finding it is not restarting automatically after reboot.

If I restart the machine, caddy is not running.

If I then run `sudo systemctl start caddy` caddy starts and runs with no errors (i.e. proving there is no fault with my configuration file or my installation)

If I then run `sudo systemctl enable caddy` there are no errors, but it has no effect on ensuring caddy starts after reboot.\

There seems to be some sort of race condition going on.

Immediately after reboot, I see the following in /var/log/daemon.log:

```
May 29 12:40:36 xyz caddy[463]: run: loading initial config: loading new config: http app module: start: tcp: listening on [my-ipv6-address]:443: listen tcp [my-ipv6-address]:443: bind: cannot assign requested address
May 29 12:40:36 xyz systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
May 29 12:40:36 xyz systemd[1]: caddy.service: Failed with result 'exit-code'.
```

**_BUT_** I can _immediately_ run `sudo systemctl start caddy`, **making no configuration changes and running no prior commands**, and caddy starts with no errors.

There is nothing special about my interface, its all static and  hardcoded in `/etc/network/interfaces` no dynamic wizzardry going on.

So it seems Caddy is trying to init before the network interface has finished init (or something like that).

**Comment by Mohammed90** [comment] 2021-06-05 00:12
I can't replicate it. I've deployed a fresh Debian 10 server, installed Caddy, rebooted it few times, and no issues of the same. Do you have custom systemd unit file besides the one shipped with the package?

**Comment by udf2457** [comment] 2021-06-08 13:20
@Mohammed90 Nope, not doing anything special like custom systemd.  I've scheduled an uninstall/reinstall of Caddy this weekend.

**Comment by udf2457** [comment] 2021-07-27 13:54
@Mohammed90

Coming back to this question for a moment.

Could I ask, on the Debian 10 system you test on, how was your network configured ?  Via some sort of network manager or `/etc/network/interfaces` ?

My environment uses `/etc/network/interfaces` and it seems this can cause problems with systemd `network-online.target` (e.g. https://unix.stackexchange.com/questions/209832/debian-systemd-network-online-target-not-working)

**Comment by francislavoie** [comment] 2021-07-27 14:01
I'm pretty sure @Mohammed90 spun up a Debian VM on DigitalOcean to test it (correct me if I'm wrong), so whatever defaults that was configured with.

You're the only one whose reported this in the year and a half since we released Caddy v2, so we don't really have evidence that this is a wide-spread issue.

I think you should use `sudo systemctl edit caddy` to set up overrides to the service installed by our deb package to make it work in your situation.

**Comment by udf2457** [comment] 2021-07-27 14:03
>  Debian VM on DigitalOcean

So this isn't a clean install of Debian ?  Its a package which might include things like NetworkManager to make it easier for users ?

Saying "I'm the only one" is unhelpful.  Maybe everyone else is using the magic cloud with ready-baked AMIs that might contain NetworkManagers ?

**Comment by francislavoie** [comment] 2021-07-27 14:13
Depends on your definition of "clean". That would be a clean installation _on DigitalOcean_ because that's the way they provide to spin up a Debian VPS. It wasn't clear before that you're doing it by hand in a VM from the ISO, that will probably make it easier to replicate.

> Saying "I'm the only one" is unhelpful. Maybe everyone else is using the magic cloud with ready-baked AMIs that might contain NetworkManagers to enable integration with cloud environments ?

What I was trying to get at is that if we can't replicate it, we can't do much to address the issue ourselves, so you're kinda on your own to debug and determine what the appropriate fix would be, and we haven't had anyone else report the same problem so we don't have anyone else to help you with it either.

> I'm not going to mess around with systemctl edit caddy, my time would be much better spent (less time involved) dumping Caddy and moving back to Nginx which works out of the box on reboots, unlike Caddy.

Well, our time is better spent not debugging and issue we can't replicate. It goes both ways. If you want this fixed, then you'll need to help us do the legwork to understand where the problem lies. If that's not worth your time, then that's fine, and we'll close the issue.

**Comment by udf2457** [comment] 2021-07-27 14:16
> > So this isn't a clean install of Debian ?

Huh ?

My definition of clean is pretty darn obvious.

You claim Debian compatability.

This means I should be able to download a Debian ISO from the Debian website, run a default install and Caddy operates correctly (including after reboot).

Relying on some third-party definition (e.g. DigitalOcean) of what is a "Debian Install" is just dumb.

**Comment by Mohammed90** [comment] 2021-07-27 21:07
For the record, yes, I did what @francislavoie said, that is I deployed a DigitalOcean image.

That said, and to go the extra mile of investigation, (I took time off my homework) I downloaded the iso from here https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/, installed it into VirtualBox, installed Caddy, and rebooted it couple of times. This is a fresh install using an iso downloaded from Debian's own website. Caddy still started automatically on every reboot. At this point I'm out of ideas on how to further look into this. Unless we can replicate it, we can't investigate it on or own. The other alternative is for the user/you to help us help them/you. You can poke around on your machine for more clues into the root cause. Once you provide more clues, we're more than happy to implement a solution.

As Francis said, had this issue been common, we would've seen more reports on here and the forum, and we would've seen upvotes on this issue report. Note how we didn't close the issue for being not being reproducible. We marked it as `needs info`.

**Closed** 2021-07-27 22:31 UTC
Labels: needs info
