### ISSUE TITLE
Digital Ocean droplet doesn’t work

### ISSUE THREAD

**Issue by RickyBubbles** [caddyserver/dist#40] opened 2020-07-12 11:21 UTC
The pre-configured digital ocean droplet maintained by the project does not work. It simply loads blank pages.

It also does not answer requests via https or on port 443.

**Comment by Mohammed90** [comment] 2020-07-12 11:45
Thank you for the report. However, the issue is not reproducible. As a proof, here's a droplet of the image deployed a few minutes ago to verify the issue, and it's working fine. Visit it here:


[http://206.189.134.81](http://206.189.134.81)


![Screenshot_20200712-144356_Chrome.jpg](https://user-images.githubusercontent.com/2636183/87245464-26764600-c44e-11ea-9030-401cbf7079b1.jpg)

**Comment by francislavoie** [comment] 2020-07-12 11:47
We'll need more information than you've provided to confirm any kind of issue.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by RickyBubbles** [comment] 2020-07-12 11:53
> Thank you for the report. However, the issue is not reproducible. As a proof, here's a droplet of the image deployed a few minutes ago to verify the issue, and it's working fine. Visit it here:
> 
> http://206.189.134.81
> 
> ![Screenshot_20200712-144356_Chrome.jpg](https://user-images.githubusercontent.com/2636183/87245464-26764600-c44e-11ea-9030-401cbf7079b1.jpg)

Did you modify the caddyfile in any way?
I guess I could have been more specific and stated that simply spinning up the droplet does not create a usable server.

**Comment by francislavoie** [comment] 2020-07-12 11:56
The server at http://206.189.134.81 is using the default Caddyfile, which only listens on port 80

https://github.com/caddyserver/dist/blob/master/config/Caddyfile

**Closed** 2020-07-12 11:58 UTC

**Comment by mholt** [comment] 2020-07-12 19:08
I am also unable to reproduce this problem. Can you post a video (without any cuts) of creating the droplet and then loading the IP and showing how it only shows a blank page?

> It also does not answer requests via https or on port 443.

Right, the instructions tell you how to get this.
