### ISSUE TITLE
Official Alpine Linux package

### ISSUE THREAD

**Issue by qu5** [caddyserver/dist#32] opened 2020-05-07 14:47 UTC
Maybe `apk add caddy2` is good for caddy and alpine

**Comment by francislavoie** [comment] 2020-05-07 14:53
Sure. Would you be able to help? I think the Alpine team handles packaging themselves.

If you're looking to use this with Docker, we have an official Docker image already: https://hub.docker.com/_/caddy/

If you need to pull Caddy into an existing image, then you can just copy the binary from the official image:

```
COPY --from=caddy:2.0.0 /usr/bin/caddy /usr/bin/caddy
```

**Comment by jiid** [comment] 2020-05-07 15:29
I've installed caddy2. And I want to start caddy2 when the system is launching like `rc-update add caddy2`

**Comment by hairyhenderson** [comment] 2020-05-07 15:44
@jiid to better understand your use-case, are you using Alpine Linux as a host OS (i.e. outside Docker)? That's a pretty rare use-case, so that's why we haven't done that yet. Though I've gone through the process for providing Alpine packages in the past.

Also note that there is currently a package for Caddy in Alpine: https://pkgs.alpinelinux.org/package/edge/community/x86_64/caddy

It's out-of-date, however.

Currently Chloe Kudryavtsev is listed as the maintainer, though I can't find their GitHub username. I do see that @maxice8 and @clandmeter have been variously active in maintaining that package in the past - perhaps one of them is interested in updating it?

(Here's the history where I'm getting that information from: https://github.com/alpinelinux/aports/commits/master/community/caddy)

**Comment by hairyhenderson** [comment] 2020-05-07 15:45
Also just a note that while I think this is the correct repo for this discussion, the `APKBUILD` itself will not reside here, it'll need to be in Alpine's `aports` repo (https://gitlab.alpinelinux.org/alpine/aports).

**Comment by Mohammed90** [comment] 2020-05-11 21:47
I've just emailed the person listed as the maintainers of the Caddy package on Alpine to arrange for the update. 🤞

**Comment by Mohammed90** [comment] 2020-05-13 18:10
Apparently gmail retries for a day or so and now says the email to the Alpine package maintainer bounced. 😕

**Comment by Mohammed90** [comment] 2020-05-15 20:12
I found this guide for anyone who'd like to take it up:

https://github.com/alpinelinux/aports/blob/master/.github/CONTRIBUTING.md

**Comment by maxice8** [comment] 2020-05-15 20:23
GitHub is deprecated and PRs will be auto-closed by a bot, one must use gitlab.alpinelinux.org to contribute

**Comment by Mohammed90** [comment] 2020-05-19 21:20
@maxice8, we have a situation where the Caddyfile syntax v2 isn't 100% compatible with v1. I believe simply upgrading the APKBUILD will break users' setup, right? What's Alpine strategy around handling breaking upgrades?

**Comment by maxice8** [comment] 2020-05-19 21:28
There are various ways to do it and it depends on discussion between the developers, out of the top of my head we can:

1. Align the upgrade with a release from Alpine Linux (3.12 is coming very soon), we can make `caddy` the v2 package, and have a caddy1 for people that need it (we also add it to the release notes so users know how to adjust their Dockerfiles and other orchestration instruments)
2. Introduce a caddy2 package and leave caddy as the v1 (This can be done at any time since it won't break anyone, people will opt-in)

If you want to make the issue known to more Alpine Linux developers there are various ways:

1. Create an issue on gitlab.alpinelinux.org/Alpine/aports
2. Bring it to attention in #alpine-devel in Freenode IRC
3. Mail it to https://lists.alpinelinux.org/~alpine/devel/

If you want i can make a MR to do the first option, hopefully we can get it merged before 3.12 is released.

**Comment by Mohammed90** [comment] 2020-05-19 21:50
> Align the upgrade with a release from Alpine Linux (3.12 is coming very soon), we can make caddy the v2 package, and have a caddy1 for people that need it (we also add it to the release notes so users know how to adjust their Dockerfiles and other orchestration instruments)

This option is the best for us to ensure users move towards v2 as they upgrade their distro. It'd be great if you can do the MR for that.
We sort of fall into [situation 1 of the Go packaging policy](https://wiki.alpinelinux.org/wiki/APKBUILD_examples:Go). However, reproducible builds can be ensured (I believe, as far as Go can go) using the Caddy builder tool, [xcaddy](https://github.com/caddyserver/xcaddy). It ensures the correct version of Caddy is embedded into the binary. If the use of external tools isn't permitted, we have a workaround using a template `.go` file as main and minimal `go.mod` to go along with that builds the same way.

**Comment by mholt** [comment] 2020-05-19 21:57
I also strongly prefer option 1 -- where `caddy` refers to v2, and another package name refers to v1 if needed.

I will ping the rest of our @caddyserver/deployment-ops team to see if they have any strong feelings in opposition to option 1.

**Comment by Conan-Kudo** [comment] 2020-05-19 22:21
If the distribution in question has a sophisticated mechanism of doing package rename transitions, then Option 1 is good.

e.g., in RPM terms, caddy1 `Obsoletes: caddy < 2.0.0` and `caddy` moves forward to 2.0.0. In this scenario, upgrades from old `caddy` will transition to `caddy1`, and `caddy` becomes free to use for version 2.

Not all distribution package managers are capable of this. I _believe_ Alpine's tooling is, though. If this does not reliably work, then Option 2 is basically mandatory until they figure out a way to switch it.

**Comment by maxice8** [comment] 2020-05-19 22:26
I don't believe apk has any equivalent to `Obsoletes:`

**Comment by Conan-Kudo** [comment] 2020-05-19 22:28
@maxice8 Is the `replaces` stanza in APKBUILD not powerful enough? Or is it that versioned declarations don't work at all? I wasn't sure if there's such a concept because I've never seen anyone do it.

**Comment by maxice8** [comment] 2020-05-19 22:34
Can't positively confirm that it can't be used but i don't see any usage of it in aports.

Also i think people will be upgraded straight to `2.0.0`

**Comment by Conan-Kudo** [comment] 2020-05-19 22:35
Then you'll need to ship caddy v2 as `caddy2` to keep it from breaking people and let them know accordingly.

**Comment by maxice8** [comment] 2020-05-19 22:40
I see but we will still need to switch caddy to 2.0.0 at one point, can't we just do it in a release since that is the point where we(Alpine Linux) are free break stuff

**Comment by mholt** [comment] 2020-05-19 22:41
Yes, let's please "break" stuff while we have the chance. :) It's very important to get people on v2 instead of v1. Especially now that the packages can be officially sanctioned, whereas they weren't before.

**Comment by maxice8** [comment] 2020-05-19 22:42
If we don't get it in by 3.12 then we will need to wait another 6 months to get 3.13 to have caddy v2 in a **stable** alpine version

**Comment by mholt** [comment] 2020-05-19 22:58
What should I do at this point to get it in 3.12? Do we just need to have a maintainer? (I don't think it can be me, I have no experience or extra time for it...)

**Comment by maxice8** [comment] 2020-05-19 23:05
1. We need to update to to 1.14.3 (we are on 1.13.x)
2. Needs someone to be maintainer for community/caddy and also community/caddy1

**Comment by maxice8** [comment] 2020-05-19 23:28
caddy 2.0.0 needs go 1.14.0 (or higher) which currently has problems with MIPS on Alpine Linux, if anyone that wants it included can have a big impact if they help in getting go 1.14.3 into Alpine Linux before the 3.12 deadline.

#alpine-devel in Freenode IRC

**Comment by Mohammed90** [comment] 2020-05-19 23:49
I see an open MR for Go 1.14.3 whose build passes on all the listed build platforms: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/8099/pipelines

MIPGS isn't listed on there though

**Comment by maxice8** [comment] 2020-05-19 23:55
That is from me, unforunately Gitlab CI still doesn't test mips, if you look at the builders in build.alpinelinux.org you will see mips64

**Comment by carlwgeorge** [comment] 2020-05-20 00:09
> e.g., in RPM terms, `caddy1` has `Obsoletes: caddy < 2.0.0` and `caddy` moves forward to 2.0.0. In this scenario, upgrades from old `caddy` will transition to `caddy1`, and `caddy` becomes free to use for version 2.

That's incorrect.  yum and dnf dependency resolution evaluates regular (same name) updates before evaluating obsoletes.  In that scenario, caddy 1.x.x installations would update to caddy 2.x.x, and a caddy1 package would only be in the upgrade path if users excluded caddy from the transaction, or explicitly asked for it.

**Comment by Mohammed90** [comment] 2020-05-20 00:16
> That is from me, unforunately Gitlab CI still doesn't test mips, if you look at the builders in build.alpinelinux.org you will see mips64

Is it related to this https://github.com/golang/go/issues/38454 ? The milestone on that bug report is 1.15, which is a bit discouraging.

**Comment by maxice8** [comment] 2020-05-20 01:40
unfortunately that is exactly it, the OP in that issue is also responsible for mips64 in Alpine Linux

**Comment by mholt** [comment] 2020-05-21 18:50
If it's really urgent, I can let my business email be the contact for this package, but I can't guarantee I'll know how to maintain it. i.e. my replies will probably be something like "Thanks -- we are looking for a maintainer. Care to help?"

**Comment by maxice8** [comment] 2020-05-21 18:58
I found someone that might be willing, the problem holding this all up is go 1.14.x  not yet working on Alpine Linux MIPS64

**Comment by maxice8** [comment] 2020-07-18 07:03
Good news: caddy 2 is in as `caddy`, caddy 1 now lives as `caddy1`

Bad news: it only arrived in Edge as 3.12 is already released

Good news: It only needs libc so it is very possible that you can add a pinned edge repo and install it basically as standalone.

**Comment by hairyhenderson** [comment] 2020-07-20 16:09
> Good news: It only needs libc so it is very possible that you can add a pinned edge repo and install it basically as standalone.

Why does it need `libc`? The official binaries are compiled with `CGO_ENABLED=0`, so maybe that's a change that needs to happen to the package 🤔

**Comment by maxice8** [comment] 2020-07-24 00:28
I'll open an issue on our GitLab instance.

**Comment by francislavoie** [comment] 2021-11-20 04:51
I think this is done, actually. The official Alpine package is being maintained by @mpolanski and @maxice8. Thanks!

**Closed by francislavoie** 2021-11-20 04:51 UTC
Labels: enhancement
